[versions]
agp = "8.0.2"
kotlin = "1.8.10"
core-ktx = "1.10.1"
coroutines = "1.7.2"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.01"
hilt = "2.43"
ksp = "1.8.0-1.0.9"
app-compat = "1.6.1"
datastore-preferences = "1.0.0"
material = "1.4.3"
timber = "5.0.1"
retrofit = '2.9.0'

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
app-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui", version = "1.4.3" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version = "1.4.3" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "1.4.3" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.4.3" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.4.3" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version = "1.4.3" }
material3 = { group = "androidx.compose.material3", name = "material3", version = "1.1.1" }
material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
material-icon = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
#coroutines-flow = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-flow", version.ref = "coroutines" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version = '5.0.0-alpha.2' }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = '5.0.0-alpha.2' }
gson = { group = "com.google.code.gson", name = "gson", version = '2.10.1' }
#jsoup = {group ="org.jsoup", nam="jsoup",version = '1.16.1'}

#hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
#hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
#hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
#hilt-ext-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltExt" }
#kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
#kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
#kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]

